# This file is for viewing cleaned data

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('cleaned_heart_2022.csv')

In [3]:
df.head(5)

,State,Sex,GeneralHealth,PhysicalHealthDays (Past 30 Days),MentalHealthDays (Past 30 Days),LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4,0,Within past year (anytime less than 12 months ...,Yes,9,None of them,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0,0,Within past year (anytime less than 12 months ...,Yes,6,None of them,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0,0,Within past year (anytime less than 12 months ...,No,8,"6 or more, but not all",No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5,0,Within past year (anytime less than 12 months ...,Yes,9,None of them,No,...,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3,15,Within past year (anytime less than 12 months ...,Yes,5,1 to 5,No,...,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [4]:
df.describe()

,PhysicalHealthDays (Past 30 Days),MentalHealthDays (Past 30 Days),SleepHours,HeightInMeters,WeightInKilograms,BMI
count,240141.000000,240141.000000,240141.000000,240141.000000,240141.000000,240141.000000
mean,4.111476,4.178512,7.026093,1.706301,83.727243,28.668279
std,8.395728,8.099787,1.437068,0.106538,21.351943,6.518453
min,0.000000,0.000000,1.000000,0.910000,28.120000,12.020000
25%,0.000000,0.000000,6.000000,1.630000,68.040000,24.250000
50%,0.000000,0.000000,7.000000,1.700000,81.650000,27.460000
75%,3.000000,4.000000,8.000000,1.780000,95.250000,31.890000
max,30.000000,30.000000,24.000000,2.410000,292.570000,97.650000

In [6]:
df["HadAsthma"].unique()

array(['No', 'Yes'], dtype=object)

In [7]:
df.columns

Index(['State', 'Sex', 'GeneralHealth', 'PhysicalHealthDays (Past 30 Days)',
       'MentalHealthDays (Past 30 Days)', 'LastCheckupTime',
       'PhysicalActivities', 'SleepHours', 'RemovedTeeth', 'HadHeartAttack',
       'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus',
       'ECigaretteUsage', 'ChestScan', 'RaceEthnicityCategory', 'AgeCategory',
       'HeightInMeters', 'WeightInKilograms', 'BMI', 'AlcoholDrinkers',
       'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'TetanusLast10Tdap',
       'HighRiskLastYear', 'CovidPos'],
      dtype='object')

In [28]:
df["PhysicalHealthDays (Past 30 Days)"].unique()

array([ 4,  0,  5,  3,  2, 25, 30, 15, 29,  8, 16, 20, 10,  9,  7,  1, 21,
        6, 27, 14, 12, 11, 13, 28, 17, 23, 24, 26, 18, 22, 19])

In [8]:
count_df = df.groupby(['State', 'SmokerStatus']).size().reset_index(name='count')

# Calculate the total counts per state
total_counts = df.groupby('State').size().reset_index(name='total')

# Merge the counts data with the total counts
percentage_df = pd.merge(count_df, total_counts, on='State')

# Calculate the percentage
percentage_df['percentage'] = (percentage_df['count'] / percentage_df['total']) * 100

In [9]:
count_df

         State                           SmokerStatus  count
0      Alabama  Current smoker - now smokes every day    206
1      Alabama  Current smoker - now smokes some days     70
2      Alabama                          Former smoker    487
3      Alabama                           Never smoked   1139
4       Alaska  Current smoker - now smokes every day    334
..         ...                                    ...    ...
199  Wisconsin                           Never smoked   3512
200    Wyoming  Current smoker - now smokes every day    229
201    Wyoming  Current smoker - now smokes some days     82
202    Wyoming                          Former smoker    686
203    Wyoming                           Never smoked   1413

[204 rows x 3 columns]

In [13]:
percentage_df[percentage_df['State'] == 'Alaska']

    State                           SmokerStatus  count  total  percentage
4  Alaska  Current smoker - now smokes every day    334   3205   10.421217
5  Alaska  Current smoker - now smokes some days    124   3205    3.868955
6  Alaska                          Former smoker    952   3205   29.703588
7  Alaska                           Never smoked   1795   3205   56.006240

In [9]:
df.columns

Index(['State', 'Sex', 'GeneralHealth', 'PhysicalHealthDays (Past 30 Days)',
       'MentalHealthDays (Past 30 Days)', 'LastCheckupTime',
       'PhysicalActivities', 'SleepHours', 'RemovedTeeth', 'HadHeartAttack',
       'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus',
       'ECigaretteUsage', 'ChestScan', 'RaceEthnicityCategory', 'AgeCategory',
       'HeightInMeters', 'WeightInKilograms', 'BMI', 'AlcoholDrinkers',
       'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'TetanusLast10Tdap',
       'HighRiskLastYear', 'CovidPos'],
      dtype='object')

In [27]:
df["HadSkinCancer"].unique()

array(['No', 'Yes'], dtype=object)

BMI: ? number

Smoking: ['Former smoker', 'Never smoked',
       'Current smoker - now smokes every day',
       'Current smoker - now smokes some days']

Alcohol Drinking: ['No', 'Yes']

Stroke: ['No', 'Yes']

Physical Health: ? number

Mental Health: ? number

Difficult Walking: ['No', 'Yes']

Sex: ['Female', 'Male']

Age Category: ['Age 65 to 69', 'Age 70 to 74', 'Age 75 to 79', 'Age 80 or older',
       'Age 50 to 54', 'Age 40 to 44', 'Age 60 to 64', 'Age 55 to 59',
       'Age 45 to 49', 'Age 35 to 39', 'Age 25 to 29', 'Age 30 to 34',
       'Age 18 to 24']

Race: ['White only, Non-Hispanic', 'Black only, Non-Hispanic',
       'Other race only, Non-Hispanic', 'Multiracial, Non-Hispanic',
       'Hispanic']

Diabetic: ['No', 'Yes', 'Yes, but only during pregnancy (female)',
       'No, pre-diabetes or borderline diabetes']

Physical Activity: ['Yes', 'No']

General Health: ['Very good', 'Fair', 'Good', 'Excellent', 'Poor']

Sleep Time: ? number

Asthma: ['No', 'Yes']

Kidney Disease: ['No', 'Yes']

Skin Cancer: ['No', 'Yes']